apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-talesb
  name: nginx-talesb
  namespace: talesb-k8s
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-talesb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-talesb
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: "500m"
          requests:
            memory: 256Mi
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
