apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-talesb
  name: nginx-talesb
  namespace: talesb-k8s
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-talesb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null 
      labels:
        app: nginx-talesb
    spec: 
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
